// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/**:remult': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/[...remult]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../../../../node_modules/.pnpm/nuxt@4.1.2_@azure+identity@4.11.1_@libsql+client@0.5.6_encoding@0.1.13__@parcel+watcher@2.5.1_32bscgwdzy2ftnjuxon63gxnoq/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}